### ISSUE TITLE
Wpvulndb license

### ISSUE THREAD

**Issue by ethicalhack3r** [Te-k/pywpvulndb#1]
Hi,

Would it be possible to list our API usage requirements along side your source code licensing, please?

Something like `The wpvulndb.com API is free for non-commercial use, but requires payment and permission for any potential commercial use.`

Many thanks,
Ryan

**Comment by Te-k** [comment]
Yes of course, just updated the readme !

**Comment by ethicalhack3r** [comment]
Awesome, thank you! :)
